spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xyz_hotel?createDatabaseIfNotExist=true
    password: 123123kajun123
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update